theme: jekyll-theme-minimal

title: Het Mehta Minimal Website
description: A ML Engineer and a Full Stack Dev.
#logo: /assets/img/logo.png  # Optional: Path to your logo image
show_downloads: true        # Optional: Shows a download button (if repo has releases)

# Optional: Social links (you can use custom ones too)


# Optional: Google Analytics

# Optional: Set the URL if using a custom domain
# url: "https://hetmehta.vercel.app/"


